from collections import namedtuple

from .stufflist import StuffList

State = namedtuple("State", ["name", "abbrev"])

states = [
    ("alabama", "al"),
    ("alaska", "ak"),
    ("arizona", "az"),
    ("arkansas", "ar"),
    ("california", "ca"),
    ("colorado", "co"),
    ("connecticut", "ct"),
    ("delaware", "de"),
    ("florida", "fl"),
    ("georgia", "ga"),
    ("hawaii", "hi"),
    ("idaho", "id"),
    ("illinois", "il"),
    ("indiana", "in"),
    ("iowa", "ia"),
    ("kansas", "ks"),
    ("kentucky", "ky"),
    ("louisiana", "la"),
    ("maine", "me"),
    ("maryland", "md"),
    ("massachusetts", "ma"),
    ("michigan", "mi"),
    ("minnesota", "mn"),
    ("mississippi", "ms"),
    ("missouri", "mo"),
    ("montana", "mt"),
    ("nebraska", "ne"),
    ("nevada", "nv"),
    ("new hampshire", "nh"),
    ("new jersey", "nj"),
    ("new mexico", "nm"),
    ("new york", "ny"),
    ("north carolina", "nc"),
    ("north dakota", "nd"),
    ("ohio", "oh"),
    ("oklahoma", "ok"),
    ("oregon", "or"),
    ("pennsylvania", "pa"),
    ("rhode island", "ri"),
    ("south carolina", "sc"),
    ("south dakota", "sd"),
    ("tennessee", "tn"),
    ("texas", "tx"),
    ("utah", "ut"),
    ("vermont", "vt"),
    ("virginia", "va"),
    ("washington", "wa"),
    ("west virginia", "wv"),
    ("wisconsin", "wi"),
    ("wyoming", "wy"),
]

states = StuffList(states, State)
